update the pubsub ce event converion logic to better align to Eventarc
GoogleCloudPlatform/functions-framework-ruby pull request #105
Opened 2021-06-09 22:03 UTC by matthewrobertson

This commit updates the CloudEvent conversion for Pubsub events to add the `messageId` and `publishedTime` from the legacy event context in order to better form to the [PubSub CloudEvent schema](https://github.com/googleapis/google-cloudevents/blob/master/proto/google/events/cloud/pubsub/v1/data.proto)

2021-06-09 22:23 UTC, anniefu approved these changes
Never looked at Ruby before, fascinating 👀 

LGTM, though the expected output JSONs in the conformance test repo need to be changed to pass conformance...

2021-06-09 22:24 UTC, anniefu requested changes
Removing approval. I didn't realize you could merge without passing all the checks if there was an approval.

2021-06-09 22:47 UTC, dazuma commented
Thanks! I'll review and merge after I get back from vaca this weekend. And yes, we should wait for the conformance tests to get updated. And yes, this repo doesn't have required checks set up. I'll get around to that.

2021-06-10 00:24 UTC, matthewrobertson commented
I can look into updating the conformance tests.

2021-06-13 22:50 UTC, dazuma approved these changes
Thanks! LGTM

2021-06-13 22:52 UTC, merged